version: "3.9"

services:
  registry:
    image: registry:2.8.1
    networks:
      - host
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /data/registry:/var/lib/registry

networks:
  host:
    external: true
    name: "host"