version: "3.9"

services:
  nginx:
    image: nginx:1.23.3-alpine
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    configs:
      - source: nginx
        target: /etc/nginx/nginx.conf
    secrets:
      - source: cakey
        target: /etc/nginx/certs/example.cc.key
        mode: 0440
      - source: cacer
        target: /etc/nginx/certs/example.cc.cer
        mode: 0440
      - source: registry
        target: /etc/nginx/registry.htpasswd
        mode: 0777
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /data/nginx/conf.d:/etc/nginx/conf.d
      - /data/nginx/web_root:/usr/share/nginx/html:ro

configs:
  nginx:
    file: ./nginx.conf

secrets:
  cakey:
    file: ./acme.sh/certs/*.example.cc.key
  cacer:
    file: ./acme.sh/certs/fullchain.cer
  registry:
    file: ./registry.htpasswd