version: "3.9"

services:
 server:
  image: mysql:8.0.33
  command: --default-authentication-plugin=mysql_native_password
  volumes:
   - /data/mysql:/var/lib/mysql:rw
   - /etc/timezone:/etc/timezone:ro
  environment:
   TZ: Asia/Shanghai
   MYSQL_ROOT_PASSWORD: password
  networks:
    - host

networks:
  host:
    external: true
    name: "host"

